version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/els-client:cached
    command: sleep infinity
networks:
  default: 
    external: 
      name: elastic_search_elastic